### ISSUE TITLE
Code arm required

### ISSUE THREAD

**Issue by pergolafabio** [markxroberts/risco-mqtt-local#46]
Hey, I see in the bete release notes a breaking change for the alarm panel, is it possible to add this value as an option? I don't want to use a code to arm/disarm...

https://developers.home-assistant.io/blog/2024/05/22/alarm_control_panel_validation/

**Comment by pergolafabio** [comment]
hey @markxroberts  .... I updated indeed to 2026.6
and the alarm panel was failing, since no code was setup, i had to define a default code, maybe an option to turn of the code_arm_required in your addon?

![image](https://github.com/markxroberts/risco-mqtt-local/assets/43251136/8a1f7eaa-1138-4e31-a411-7c65109354b5)

**Comment by markxroberts** [comment]
Well spotted.  I didn't notice that it was a breaking change.

There's no facility to validate the code against the panel.  The easiest option is for me to specify ```code_alarm_required: false``` in the registration packet.

If I put it in as an option, I'll have to validate it in the add-on, which doesn't seem right.  Is that OK?  If you say yes, I'll try to release an update later.

**Comment by pergolafabio** [comment]
indeed, code_alarm_required: false, is perfect :-)
i have now setup a default code in the alarm panel, otherwhise it wasnt working anymore

**Comment by markxroberts** [comment]
Should be closed by #47, release 2024.6.1

**Comment by pergolafabio** [comment]
Great! :-)

**Comment by pergolafabio** [comment]
Hey, i saw some updates, thnx
@markxroberts , any idea why the lovelace alarm panel card is now presenting a keycode pad?

Never had this before :-(

![image](https://github.com/markxroberts/risco-mqtt-local/assets/43251136/87db19bc-c9a4-4681-9218-db2e83edaf31)
![image](https://github.com/markxroberts/risco-mqtt-local/assets/43251136/eb572f44-c9b0-499a-a30b-dfd36e48cde9)

**Comment by markxroberts** [comment]
Which add-on version is that?

**Comment by pergolafabio** [comment]
I'm running latest version, updated yesterday, but not sure if it's addon related

**Comment by markxroberts** [comment]
2024.6.2 only released this morning.  Could be an issue with the earlier version, but as no code specified in that one, seems less likely, especially as the configuration you shared is ```code_arm_required: false```.

**Comment by pergolafabio** [comment]
Yeah, nor sure what's going on :-(

**Comment by pergolafabio** [comment]
Seems there is also "code_disarm_required"  , maybe that one is needed to for "false" setting to hide the new keypad?
see here:

https://github.com/home-assistant/core/issues/119443

**Comment by markxroberts** [comment]
Both ```"code_arm_required": false``` and ```"code_disarm_required": false``` are already present in the HA autodiscovery message for the partitions from 2024.6.1 onwards.

**Comment by pergolafabio** [comment]
ah, but i only see this one: code_arm_required: false

![image](https://github.com/markxroberts/risco-mqtt-local/assets/43251136/ef3f7c16-7bdb-40a3-a47a-f00e39858513)

**Comment by markxroberts** [comment]
You may need to update to the latest version.  I can't remember when I noticed that both entries were required.

**Comment by pergolafabio** [comment]
Just updated, but still a keypad, still notice only: code_arm_required

**Comment by markxroberts** [comment]
Can you pls share the MQTT autodiscovery message using MQTT explorer or equivalent

**Comment by pergolafabio** [comment]
hmm, seems its there, but i dont see it, even after restarting the addon

`{"name":"Pergola Quintens","object_id":"risco-alarm-panel-1","state_topic":"risco-alarm-panel/alarm/partition/1/status","unique_id":"risco-alarm-panel-partition-1","availability_mode":"all","availability":[{"topic":"risco-alarm-panel/alarm/status"},{"topic":"risco-alarm-panel/alarm/button_status"}],"payload_disarm":"disarmed","payload_arm_away":"armed_away","payload_arm_home":"armed_home","payload_arm_night":"armed_home","payload_arm_vacation":"armed_away","payload_arm_custom_bypass":"armed_home","code_arm_required":false,"code_disarm_required":false,"code":XXX,"device":{"manufacturer":"Risco","model":"LightSys/RP432","name":"Risco Alarm","sw_version":"2.70","identifiers":"risco-alarm-panel"},"command_topic":"risco-alarm-panel/alarm/partition/1/set"}`

![image](https://github.com/markxroberts/risco-mqtt-local/assets/43251136/ee364307-36df-4c37-9171-0ecb468c7ec9)

**Comment by pergolafabio** [comment]
tried deleting the mqtt device and restarted addon, to start clean, but didnt make any difference
but i still dont know if it will fix the keypad issue at the end

**Comment by pergolafabio** [comment]
ok, yeah, it started happening since 2024.6.x , i try to keep away from custom cards if not needed :-)
maybe i can hide it with card-mod

**Comment by pergolafabio** [comment]
found this on forum, working for now :-)

```
          - type: alarm-panel
            entity: alarm_control_panel.risco_alarm
            card_mod:
              style: |
                  #keypad {display: none !important;}
                  ha-textfield {display: none !important;}
```

**Comment by pergolafabio** [comment]
Hey, thnx for updating this addon!! Really like it!!
